---
repos:
  - repo: local
    hooks:
      - id: lint
        name: Run lint code
        description: This hook run local executable linter at `bin/lint.sh`
        entry: bin/lint.sh --fix
        language: python
        types: [text]
        pass_filenames: false
      - id: check-dependencies
        name: Check poetry dependencies
        description: This hook run local executable dependencies checker at `bin/dep-validate.sh`
        entry: bin/dep-validate.sh
        language: python
        types: [ text ]
        pass_filenames: false
